//created on: 7 nov. 2020
package bruxismo

import model.Persona
import model.AlineacionDeDientes
import model.Postura
import model.Estres
import model.Insomnio
import model.Depresion
import model.Diagnostico
import model.DiagnosticoFinal


rule "R1"

    when
        $diagnostico:Diagnostico(persona.getAlineacionDeDientes() == AlineacionDeDientes.MAL)
    then
		modify($diagnostico) {
    		setTendenciaABruxismo(true);
    	}
    	   
end

rule "R2"

    when
        $diagnostico:Diagnostico(persona.getHabitoDeApretarLosDientes() == true)
    then
		modify($diagnostico) {
    		setTendenciaABruxismo(true);
    	}
    	   
end

rule "R3"

    when
        $diagnostico:Diagnostico(persona.getAlineacionDeDientes() == AlineacionDeDientes.REGULAR 
        						&& persona.getPostura() == Postura.MAL)
    then
		modify($diagnostico) {
    		setTendenciaABruxismo(true);
    	}
    	   
end

rule "R4"

	when
		$diagnostico:Diagnostico(persona.getContexto().getEstres() == Estres.SI)
	then
		modify($diagnostico) {
			setContextoDesfavorable(true);
		}
		
end

rule "R5"

	when
		$diagnostico:Diagnostico(persona.getContexto().getInsomnio() == Insomnio.SI
								&& persona.getContexto().getDepresion() == Depresion.SI)
	then
		modify($diagnostico) {
			setContextoDesfavorable(true);
		}
		
end

rule "R6"

	when
		$diagnostico:Diagnostico()
				
		Persona( getSintomas().getPresentaDolorFacial(),
				getPresentaSintomas() == false) from $diagnostico.persona
	then
		modify($diagnostico) {
			persona.setPresentaSintomas(true);
		}
		
end

rule "R7"

	when
		$diagnostico:Diagnostico()
				
		Persona( getSintomas().getPresentaDolorDeCabeza(),
				getPresentaSintomas() == false) from $diagnostico.persona
	then
		modify($diagnostico) {
			persona.setPresentaSintomas(true);
		}
		
end

rule "R8"

	when
		$diagnostico:Diagnostico()
				
		Persona( getSintomas().getPresentaDolorDeOido(),
				getPresentaSintomas() == false) from $diagnostico.persona
	then
		modify($diagnostico) {
			persona.setPresentaSintomas(true);
		}
		
end

rule "R9"

	when
		$diagnostico:Diagnostico()
				
		Persona( getSintomas().getPresentaDesgasteDental(),
				getPresentaSintomas() == false) from $diagnostico.persona
	then
		modify($diagnostico) {
			persona.setPresentaSintomas(true);
		}
		
end

rule "R10"

	when
		$diagnostico:Diagnostico()
				
		Persona( getSintomas().getPresentaInflamaciónDeMandibula(),
				getPresentaSintomas() == false) from $diagnostico.persona
	then
		modify($diagnostico) {
			persona.setPresentaSintomas(true);
		}
		
end

rule "R11"

	when
		$diagnostico:Diagnostico(persona.getPresentaSintomas() && tendenciaABruxismo && contextoDesfavorable)
	then
		modify($diagnostico) {
			setDiagnosticoFinal(DiagnosticoFinal.COMPATIBLE_BRUXISMO);
		}
		
end
